# Site settings
title:          atabek.me
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         Atabek
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10

defaults:
  - scope:
      path: "_posts/lat"
      type: "posts"
    values:
      permalink: "lat/:year/:month/:day/:title"
      language: lat
  - scope:
      path: "_posts/cyr"
      type: "posts"
    values:
      permalink: "cyr/:year/:month/:day/:title"
      language: cyr

